import { useEffect, useState } from "react";

import {
  HandCoins,
  CheckCircle2,
  Download,
} from "lucide-react";

import MainLayout from "../layouts/MainLayout";

import api from "../services/api";

import jsPDF from "jspdf";

function FineLedgerPage() {

  // STATES

  const [fines, setFines] =
    useState([]);

  const [loading, setLoading] =
    useState(true);


  // FETCH FINES

  async function fetchFines() {

    try {

      const response =
        await api.get(
          "/fines"
        );

      setFines(
        response.data
      );

    }

    catch (error) {

      console.log(error);

    }

    finally {

      setLoading(false);

    }

  }


  // PAGE LOAD

  useEffect(() => {

    fetchFines();

  }, []);


  // PAY FINE

  async function handlePayFine(
    fineId
  ) {

    try {

      await api.put(
        `/fines/${fineId}/pay`
      );

      fetchFines();

    }

    catch (error) {

      alert(
        error.response?.data?.message ||
        "Failed to pay fine"
      );

    }

  }


  // DOWNLOAD INVOICE

  const downloadInvoice = (
    fine
  ) => {

    const doc =
      new jsPDF();


    // TITLE

    doc.setFontSize(24);

    doc.text(
      "Lexora Fine Invoice",
      20,
      25
    );


    // LINE

    doc.line(
      20,
      32,
      190,
      32
    );


    // DETAILS

    doc.setFontSize(14);

    doc.text(
      `Member Name: ${
        fine.user_name
      }`,
      20,
      55
    );

    doc.text(
      `Book Title: ${
        fine.book_title
      }`,
      20,
      70
    );

    doc.text(
      `Fine Amount: ₹${
        fine.amount
      }`,
      20,
      85
    );

    doc.text(
      `Payment Status: ${
        fine.paid_status
          ? "Paid"
          : "Pending"
      }`,
      20,
      100
    );


    // FOOTER

    doc.setFontSize(12);

    doc.text(
      "Smart Library. Seamless Experience.",
      20,
      165
    );

    doc.text(
      "Generated by Lexora LMS",
      20,
      180
    );


    // SAVE

    doc.save(
      `fine_invoice_${fine.id}.pdf`
    );

  };


  return (

    <MainLayout>

      {/* HEADER */}

      <div
        className="
          mb-10
        "
      >

        <h1
          className="
            text-5xl
            font-serif
            font-bold
            text-slate-900
            mb-3
          "
        >
          Fine Ledger
        </h1>


        <p
          className="
            text-gray-500
            text-lg
          "
        >
          Manage fines and overdue penalties.
        </p>

      </div>


      {/* TABLE */}

      <div
        className="
          bg-white
          border
          border-gray-200
          rounded-3xl
          overflow-hidden
        "
      >

        {/* HEADER */}

        <div
          className="
            grid
            grid-cols-[2fr_2fr_1fr_1fr_1fr_1fr]
            px-8
            py-5
            bg-gray-50
            text-sm
            font-medium
            text-gray-500
          "
        >

          <div>User</div>

          <div>Book</div>

          <div>Amount</div>

          <div>Status</div>

          <div>Action</div>

          <div>Invoice</div>

        </div>


        {/* BODY */}

        {loading ? (

          <div
            className="
              p-10
              text-center
              text-gray-500
            "
          >

            Loading fines...

          </div>

        ) : fines.length === 0 ? (

          <div
            className="
              p-10
              text-center
              text-gray-500
            "
          >

            No fines available.

          </div>

        ) : (

          fines.map((fine) => (

            <div
              key={fine.id}
              className="
                grid
                grid-cols-[2fr_2fr_1fr_1fr_1fr_1fr]
                items-center
                px-8
                py-6
                border-t
                border-gray-100
                hover:bg-gray-50
                transition
              "
            >

              {/* USER */}

              <div>

                <h3
                  className="
                    text-[18px]
                    font-semibold
                    text-slate-900
                  "
                >

                  {fine.user_name}

                </h3>

              </div>


              {/* BOOK */}

              <div>

                <h3
                  className="
                    text-[18px]
                    font-semibold
                    text-slate-900
                  "
                >

                  {fine.book_title}

                </h3>

              </div>


              {/* AMOUNT */}

              <div
                className="
                  text-red-600
                  font-semibold
                  text-lg
                "
              >

                ₹{fine.amount}

              </div>


              {/* STATUS */}

              <div>

                <span
                  className={`
                    px-3
                    py-1.5
                    rounded-lg
                    text-sm
                    font-medium

                    ${
                      fine.paid_status

                        ? "bg-green-100 text-green-700"

                        : "bg-red-100 text-red-700"
                    }
                  `}
                >

                  {fine.paid_status
                    ? "Paid"
                    : "Unpaid"}

                </span>

              </div>


              {/* PAY BUTTON */}

              <div>

                {!fine.paid_status ? (

                  <button

                    onClick={() =>
                      handlePayFine(
                        fine.id
                      )
                    }

                    className="
                      flex
                      items-center
                      gap-2
                      bg-slate-900
                      text-white
                      px-4
                      py-2
                      rounded-xl
                      hover:bg-slate-800
                      transition
                    "
                  >

                    <HandCoins size={16} />

                    Pay

                  </button>

                ) : (

                  <div
                    className="
                      flex
                      items-center
                      gap-2
                      text-green-600
                      font-medium
                    "
                  >

                    <CheckCircle2 size={18} />

                    Paid

                  </div>

                )}

              </div>


              {/* DOWNLOAD */}

              <div>

                <button

                  onClick={() =>
                    downloadInvoice(fine)
                  }

                  className="
                    flex
                    items-center
                    gap-2
                    bg-slate-900
                    text-white
                    px-4
                    py-2
                    rounded-xl
                    hover:bg-slate-800
                    transition
                    text-sm
                    font-medium
                  "
                >

                  <Download size={16} />

                  Download

                </button>

              </div>

            </div>

          ))

        )}

      </div>

    </MainLayout>

  );

}

export default FineLedgerPage;