import { useEffect, useState } from "react";

import {
  Clock3,
  BookOpen,
  CheckCircle2,
  AlertTriangle,
} from "lucide-react";

import MainLayout from "../layouts/MainLayout";

import jsPDF from "jspdf";

import api from "../services/api";

function MyBorrowsPage() {

  // USER

  const user =
    JSON.parse(
      localStorage.getItem("user")
    );


  // STATES

  const [records, setRecords] =
    useState([]);

  const [loading, setLoading] =
    useState(true);


  // FETCH BORROWS

  async function fetchBorrows() {

    try {

      const response =
        await api.get(
          "/borrow"
        );


      // CURRENT USER ONLY

      const myRecords =
        response.data.filter(
          (record) =>
            record.user_id === user.id
        );


      setRecords(myRecords);

    }

    catch (error) {

      console.log(error);

    }

    finally {

      setLoading(false);

    }

  }


  // PAGE LOAD

  useEffect(() => {

    fetchBorrows();

  }, []);


  // DOWNLOAD RECEIPT

  const downloadReceipt = (
    record
  ) => {

    const doc =
      new jsPDF();


    // TITLE

    doc.setFontSize(24);

    doc.text(
      "Lexora Library Receipt",
      20,
      25
    );


    // LINE

    doc.line(
      20,
      32,
      190,
      32
    );


    // DETAILS

    doc.setFontSize(14);

    doc.text(
      `Member Name: ${
        user.name
      }`,
      20,
      55
    );

    doc.text(
      `Book Title: ${
        record.book_title
      }`,
      20,
      70
    );

    doc.text(
      `Status: ${
        record.status
      }`,
      20,
      85
    );

    doc.text(
      `Borrow Date: ${
        new Date(
          record.borrow_date
        ).toLocaleDateString()
      }`,
      20,
      100
    );

    doc.text(
      `Due Date: ${
        new Date(
          record.due_date
        ).toLocaleDateString()
      }`,
      20,
      115
    );


    // FOOTER

    doc.setFontSize(12);

    doc.text(
      "Smart Library. Seamless Experience.",
      20,
      165
    );

    doc.text(
      "Generated by Lexora LMS",
      20,
      180
    );


    // SAVE

    doc.save(
      `receipt_${record.id}.pdf`
    );

  };


  return (

    <MainLayout>

      {/* HEADER */}

      <div
        className="
          mb-10
        "
      >

        <h1
          className="
            text-5xl
            font-serif
            font-bold
            text-slate-900
            mb-3
          "
        >
          My Borrows
        </h1>


        <p
          className="
            text-gray-500
            text-lg
          "
        >
          Track all your borrowed books and requests.
        </p>

      </div>


      {/* TABLE */}

      <div
        className="
          bg-white
          border
          border-gray-200
          rounded-3xl
          overflow-hidden
        "
      >

        {/* TABLE HEADER */}

        <div
          className="
            grid
            grid-cols-[2fr_1.3fr_1.3fr_1fr_1fr]
            px-8
            py-5
            bg-gray-50
            text-sm
            font-medium
            text-gray-500
          "
        >

          <div>Book</div>

          <div>Borrow Date</div>

          <div>Due Date</div>

          <div>Status</div>

          <div>Receipt</div>

        </div>


        {/* TABLE BODY */}

        {loading ? (

          <div
            className="
              p-10
              text-center
              text-gray-500
            "
          >

            Loading borrows...

          </div>

        ) : records.length === 0 ? (

          <div
            className="
              p-10
              text-center
              text-gray-500
            "
          >

            No borrow records found.

          </div>

        ) : (

          records.map((record) => (

            <div
              key={record.id}
              className="
                grid
                grid-cols-[2fr_1.3fr_1.3fr_1fr_1fr]
                items-center
                px-8
                py-6
                border-t
                border-gray-100
                hover:bg-gray-50
                transition
              "
            >

              {/* BOOK */}

              <div
                className="
                  flex
                  items-center
                  gap-4
                "
              >

                <div
                  className="
                    w-12
                    h-12
                    rounded-2xl
                    bg-gray-100
                    flex
                    items-center
                    justify-center
                    text-slate-700
                  "
                >

                  <BookOpen size={20} />

                </div>


                <div>

                  <h3
                    className="
                      text-[18px]
                      font-semibold
                      text-slate-900
                    "
                  >

                    {record.book_title}

                  </h3>

                </div>

              </div>


              {/* BORROW DATE */}

              <div
                className="
                  text-gray-600
                "
              >

                {new Date(
                  record.borrow_date
                ).toLocaleDateString()}

              </div>


              {/* DUE DATE */}

              <div
                className="
                  text-gray-600
                "
              >

                {new Date(
                  record.due_date
                ).toLocaleDateString()}

              </div>


              {/* STATUS */}

              <div>

                <span
                  className={`
                    flex
                    items-center
                    gap-2
                    w-fit
                    px-3
                    py-1.5
                    rounded-lg
                    text-sm
                    font-medium

                    ${
                      record.status ===
                      "Approved"

                        ? "bg-green-100 text-green-700"

                        : record.status ===
                          "Rejected"

                        ? "bg-red-100 text-red-700"

                        : record.status ===
                          "Returned"

                        ? "bg-blue-100 text-blue-700"

                        : record.status ===
                          "Overdue"

                        ? "bg-orange-100 text-orange-700"

                        : "bg-yellow-100 text-yellow-700"
                    }
                  `}
                >

                  {record.status ===
                  "Approved" ? (

                    <CheckCircle2 size={16} />

                  ) : record.status ===
                    "Rejected" ? (

                    <AlertTriangle size={16} />

                  ) : (

                    <Clock3 size={16} />

                  )}

                  {record.status || "Pending"}

                </span>

              </div>


              {/* DOWNLOAD */}

              <div>

                <button

                  onClick={() =>
                    downloadReceipt(record)
                  }

                  className="
                    bg-slate-900
                    text-white
                    px-4
                    py-2
                    rounded-xl
                    hover:bg-slate-800
                    transition
                    text-sm
                    font-medium
                  "
                >

                  Download

                </button>

              </div>

            </div>

          ))

        )}

      </div>

    </MainLayout>

  );

}

export default MyBorrowsPage;